name: Build module firmware

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository including submodules
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - uses: actions/cache@v3
        with:
          path: |
            /opt/avr-libc
          key: ${{ runner.os }}-avrlibc

      # Install dependencies
      - name: Install gcc-avr and cmake
        run: |
          sudo apt-get update 
          sudo apt-get install -y gcc-avr avr-libc cmake

          mkdir /opt/avr-libc
          cd /opt/avr-libc
          # Install AVR Libc from the specified URL
          wget https://github.com/avrdudes/avr-libc/releases/download/avr-libc-2_2_1-release/avr-libc-2.2.1.tar.bz2
          tar -xf avr-libc-2.2.1.tar.bz2
          cd avr-libc-2.2.1
          # Build and install AVR Libc
          ./configure --build=`./config.guess` --host=avr --prefix=/usr
          make
          sudo make install

      # Configure and build using CMake
      - name: Build with CMake
        run: |
         cmake --toolchain avr-gcc.toolchain.cmake -B build . 
         make -C build

      # Upload firmware binaries
      - name: Upload firmware binaries
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/src/mfm-sensor-module-attiny1614.elf
            build/src/mfm-sensor-module-attiny1614.hex
